# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('result_text', models.TextField(blank=True, null=True)),
                ('offset', models.CharField(max_length=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('encryption', models.BooleanField(default=True)),
            ],
        ),
    ]
